
--tüm verileri çağırma
select*from USERS
select*from ORDERS
select*from ORDERDETAILS
select*from ADDRESS
select*from CITIES
select*from COUNTRIES
select*from ITEMS
select*from TOWNS
select*from PAYMENTS
select*from DISTRICTS
select*from INVOICES
select*from INVOICEDETAILS


--Şehirlere göre verilen siparişleri listeleme
SELECT
C.CITY,SUM(O.TOTALPRICE) AS TOPLAM_SATIŞ
FROM USERS U 
JOIN ADDRESS A ON U.ID=A.USERID
JOIN ORDERS O ON O.ID= U.ID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN CITIES C ON C.ID=A.CITYID
JOIN COUNTRIES CT ON CT.ID=A.COUNTRYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID
GROUP BY C.CITY
ORDER BY TOPLAM_SATIŞ



-- Ürün kategorilerine göre sipariş dağılımı
SELECT
I.CATEGORY1,I.CATEGORY2,I.CATEGORY3,I.CATEGORY4,SUM(O.TOTALPRICE) AS TOPLAM_SATIŞ
FROM USERS U 
JOIN ADDRESS A ON U.ID=A.USERID
JOIN ORDERS O ON O.ID= U.ID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN CITIES C ON C.ID=A.CITYID
JOIN COUNTRIES CT ON CT.ID=A.COUNTRYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID
JOIN ITEMS I ON I.ID=OD.ITEMID
GROUP BY  I.CATEGORY1,I.CATEGORY2,I.CATEGORY3,I.CATEGORY4
ORDER BY TOPLAM_SATIŞ


--Müşterilere  göre  sipariş dağılımı
SELECT
u.NAMESURNAME,SUM(O.TOTALPRICE) AS TOPLAM_SATIŞ
FROM USERS U 
JOIN ADDRESS A ON U.ID=A.USERID
JOIN ORDERS O ON O.ID= U.ID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN CITIES C ON C.ID=A.CITYID
JOIN COUNTRIES CT ON CT.ID=A.COUNTRYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID
JOIN ITEMS I ON I.ID=OD.ITEMID
GROUP BY U.NAMESURNAME
order by TOPLAM_SATIŞ desc


--müşteri cinsiyetine göre sipariş dağılımı
SELECT
CASE 
	when u.GENDER='E' then 'ERKEK'
	when u.GENDER='K' then 'KADIN'
END AS GENDER1, 
u.GENDER,SUM(O.TOTALPRICE) AS TOPLAM_SATIŞ
FROM USERS U 
JOIN ADDRESS A ON U.ID=A.USERID
JOIN ORDERS O ON O.ID= U.ID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN CITIES C ON C.ID=A.CITYID
JOIN COUNTRIES CT ON CT.ID=A.COUNTRYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID
JOIN ITEMS I ON I.ID=OD.ITEMID
group by u.GENDER
order by TOPLAM_SATIŞ desc


--Ödeme türüne göre sipariş dağılımı
SELECT
IIF(PAYMENTTYPE=1 ,'BANKA_KARTI','KREDÝ KARTI')  AS PAYMENT_CARD,
SUM(PAYMENTTOTAL) AS TOPLAM_ÖDEME
FROM PAYMENTS 
GROUP BY PAYMENTTYPE


--Şehirlerin haftalarına göre sipariş dağılımı
SELECT
C.CITY,DATEPART(DW,DATE_) AS HAFTANIN_GÜNLERİ,DATENAME(DW,DATE_)AS HAFTANIN_GÜNLERI_AD,SUM(O.TOTALPRICE) AS TOPLAM_SATIŞ
FROM USERS U 
JOIN ADDRESS A ON U.ID=A.USERID
JOIN ORDERS O ON O.ID= U.ID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN CITIES C ON C.ID=A.CITYID
GROUP BY C.CITY,DATEPART(DW,DATE_),DATENAME(DW,DATE_)
ORDER BY C.CITY

--Siparişlerin ortalama kargo sürelerini getirme
SELECT
C.CITY,AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_)) AS ORT_KARGO_SÜRELERI,ROUND(SUM(O.TOTALPRICE),2) AS TOPLAM_SATIŞ
FROM USERS U 
JOIN ADDRESS A ON U.ID=A.USERID
JOIN ORDERS O ON O.ID= U.ID
JOIN CITIES C ON C.ID=A.CITYID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN INVOICES I ON I.ADDRESSID=A.ID
GROUP BY C.CITY
ORDER BY TOPLAM_SATIŞ


--Tüm kullanıcıların isim, e-posta ve şehir bilgilerini listele
SELECT DISTINCT
U.NAMESURNAME,U.EMAIL,C.CITY
FROM USERS U 
JOIN ADDRESS A ON U.ID=A.USERID
JOIN ORDERS O ON O.ID= U.ID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN CITIES C ON C.ID=A.CITYID
JOIN COUNTRIES CT ON CT.ID=A.COUNTRYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID
ORDER BY U.NAMESURNAME


--Her siparişin tarihini, toplam tutarını ve kullanıcı bilgisini listele
SELECT 
U.NAMESURNAME,U.EMAIL,O.DATE_,A.ADDRESSTEXT, U.TELNR1,U.TELNR2, SUM(OD.AMOUNT) AS TOPLAM_MİKTAR ,SUM(O.TOTALPRICE) AS TOPLAM_SATIŞ
FROM USERS U 
JOIN ADDRESS A ON U.ID=A.USERID
JOIN ORDERS O ON O.ID= U.ID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN CITIES C ON C.ID=A.CITYID
JOIN COUNTRIES CT ON CT.ID=A.COUNTRYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID
GROUP BY U.NAMESURNAME,U.EMAIL,O.DATE_,A.ADDRESSTEXT, U.TELNR1,U.TELNR2
ORDER BY U.NAMESURNAME


--Hangi ürünlerin en fazla satıldığı ve toplam satış miktarını gösterme
SELECT TOP 5
I.ItemName, I.CATEGORY1,I.CATEGORY2,SUM(OD.AMOUNT) AS Total_AMOUNT
FROM ITEMS I
JOIN ORDERDETAILS OD ON I.ID=OD.ITEMID
GROUP BY I.ItemName, I.CATEGORY1,I.CATEGORY2
ORDER BY Total_AMOUNT DESC;


--Her ilçede bulunan  kullanıcıların sayısını gösterme
SELECT
D.DISTRICT,count(o.USERID) as kullanıcı_sayısı
FROM USERS U 
JOIN ADDRESS A ON U.ID=A.USERID
JOIN ORDERS O ON O.ID= U.ID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN CITIES C ON C.ID=A.CITYID
JOIN COUNTRIES CT ON CT.ID=A.COUNTRYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID
JOIN ITEMS I ON I.ID=OD.ITEMID
GROUP by D.DISTRICT


--Belirli bir tarih aralığında (örneğin :2019-02-21 ile 2019-02-21) verilen siparişlerin toplam sayısını gösterme
SELECT
CONVERT(DATE,O.DATE_) as tarih  ,count(O.ID) AS Sipariş_toplam_sayısı
FROM USERS U 
JOIN ADDRESS A ON U.ID=A.USERID
JOIN ORDERS O ON O.ID= U.ID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN CITIES C ON C.ID=A.CITYID
JOIN COUNTRIES CT ON CT.ID=A.COUNTRYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID
JOIN ITEMS I ON I.ID=OD.ITEMID
where O.DATE_ between '2019-02-21' and '2019-02-21'
GROUP by CONVERT(DATE,O.DATE_)



--belirli bir şehirlerde ("Istanbul" /"Ankara"/"Karabük") verilen tüm siparişlerin toplam tutarını listele
SELECT
C.CITY  ,sum(OD.AMOUNT) AS Sipariş_toplam_tutar
FROM USERS U 
JOIN ADDRESS A ON U.ID=A.USERID
JOIN ORDERS O ON O.ID= U.ID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN CITIES C ON C.ID=A.CITYID
JOIN COUNTRIES CT ON CT.ID=A.COUNTRYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID
JOIN ITEMS I ON I.ID=OD.ITEMID
where C.CITY IN('ISTANBUL','ADANA','KARABÜK')
GROUP by C.CITY


--Şehir bazında en fazla sipariş verilen ilk 5 şehri göster
SELECT top 5
C.CITY  ,sum(OD.AMOUNT) AS Sipariş_toplam_tutar
FROM USERS U 
JOIN ADDRESS A ON U.ID=A.USERID
JOIN ORDERS O ON O.ID= U.ID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN CITIES C ON C.ID=A.CITYID
JOIN COUNTRIES CT ON CT.ID=A.COUNTRYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID
JOIN ITEMS I ON I.ID=OD.ITEMID
GROUP by C.CITY
ORDER BY Sipariş_toplam_tutar DESC


-- kullanıcıların sipariş başına ortalama ne kadar ödeme yaptığını gösterme
SELECT 
U.NAMESURNAME,ROUND(AVG(O.TOTALPRICE),2) AS Sipariş_ortalama_ödeme
FROM USERS U 
JOIN ADDRESS A ON U.ID=A.USERID
JOIN ORDERS O ON O.ID= U.ID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN CITIES C ON C.ID=A.CITYID
JOIN COUNTRIES CT ON CT.ID=A.COUNTRYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID
JOIN ITEMS I ON I.ID=OD.ITEMID
GROUP by U.NAMESURNAME
ORDER BY Sipariş_ortalama_ödeme DESC


--Ürün  markasına göre satış miktarları
SELECT 
BRAND,SUM(OD.AMOUNT) AS SATIŞ_MIKTARI
FROM USERS U 
JOIN ADDRESS A ON U.ID=A.USERID
JOIN ORDERS O ON O.ID= U.ID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN CITIES C ON C.ID=A.CITYID
JOIN COUNTRIES CT ON CT.ID=A.COUNTRYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID
JOIN ITEMS I ON I.ID=OD.ITEMID
GROUP by I.BRAND
ORDER BY SATIŞ_MIKTARI DESC



--ülkelere göre verilen toplam sipariş sayısını gösterme
SELECT 
CT.COUNTRY,COUNT(OD.ORDERID) AS SİPARİŞ_SAYISI
FROM USERS U 
JOIN ADDRESS A ON U.ID=A.USERID
JOIN ORDERS O ON O.ID= U.ID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN CITIES C ON C.ID=A.CITYID
JOIN COUNTRIES CT ON CT.ID=A.COUNTRYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID
JOIN ITEMS I ON I.ID=OD.ITEMID
GROUP by CT.COUNTRY
ORDER BY  SİPARİŞ_SAYISI DESC


