
--tüm verileri çaðýrma
select*from USERS
select*from ORDERS
select*from ORDERDETAILS
select*from ADDRESS
select*from CITIES
select*from COUNTRIES
select*from ITEMS
select*from TOWNS
select*from PAYMENTS
select*from DISTRICTS
select*from INVOICES
select*from INVOICEDETAILS


--þehirlere göre verilen sipariþleri listeleme
SELECT
C.CITY,SUM(O.TOTALPRICE) AS TOPLAM_SATIÞ
FROM USERS U 
JOIN ADDRESS A ON U.ID=A.USERID
JOIN ORDERS O ON O.ID= U.ID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN CITIES C ON C.ID=A.CITYID
JOIN COUNTRIES CT ON CT.ID=A.COUNTRYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID
GROUP BY C.CITY
ORDER BY TOPLAM_SATIÞ



-- Ürün kategorilerine göre sipariþ daðýlýmý
SELECT
I.CATEGORY1,I.CATEGORY2,I.CATEGORY3,I.CATEGORY4,SUM(O.TOTALPRICE) AS TOPLAM_SATIÞ
FROM USERS U 
JOIN ADDRESS A ON U.ID=A.USERID
JOIN ORDERS O ON O.ID= U.ID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN CITIES C ON C.ID=A.CITYID
JOIN COUNTRIES CT ON CT.ID=A.COUNTRYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID
JOIN ITEMS I ON I.ID=OD.ITEMID
GROUP BY  I.CATEGORY1,I.CATEGORY2,I.CATEGORY3,I.CATEGORY4
ORDER BY TOPLAM_SATIÞ


--Müþterilere  göre  sipariþ daðýlýmý
SELECT
u.NAMESURNAME,SUM(O.TOTALPRICE) AS TOPLAM_SATIÞ
FROM USERS U 
JOIN ADDRESS A ON U.ID=A.USERID
JOIN ORDERS O ON O.ID= U.ID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN CITIES C ON C.ID=A.CITYID
JOIN COUNTRIES CT ON CT.ID=A.COUNTRYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID
JOIN ITEMS I ON I.ID=OD.ITEMID
GROUP BY U.NAMESURNAME
order by TOPLAM_SATIÞ desc


--müþteri cinsiyetine göre sipariþ daðýlýmý
SELECT
CASE 
	when u.GENDER='E' then 'ERKEK'
	when u.GENDER='K' then 'KADIN'
END AS GENDER1, 
u.GENDER,SUM(O.TOTALPRICE) AS TOPLAM_SATIÞ
FROM USERS U 
JOIN ADDRESS A ON U.ID=A.USERID
JOIN ORDERS O ON O.ID= U.ID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN CITIES C ON C.ID=A.CITYID
JOIN COUNTRIES CT ON CT.ID=A.COUNTRYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID
JOIN ITEMS I ON I.ID=OD.ITEMID
group by u.GENDER
order by TOPLAM_SATIÞ desc


--Ödeme türüne göre sipariþ daðýlýmý
SELECT
IIF(PAYMENTTYPE=1 ,'BANKA_KARTI','KREDÝ KARTI')  AS PAYMENT_CARD,
SUM(PAYMENTTOTAL) AS TOPLAM_ÖDEME
FROM PAYMENTS 
GROUP BY PAYMENTTYPE


--Þehirlerin haftalarýna göre sipariþ daðýlýmý
SELECT
C.CITY,DATEPART(DW,DATE_) AS HAFTANIN_GÜNLERÝ,DATENAME(DW,DATE_)AS HAFTANIN_GÜNLERÝ_AD,SUM(O.TOTALPRICE) AS TOPLAM_SATIÞ
FROM USERS U 
JOIN ADDRESS A ON U.ID=A.USERID
JOIN ORDERS O ON O.ID= U.ID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN CITIES C ON C.ID=A.CITYID
GROUP BY C.CITY,DATEPART(DW,DATE_),DATENAME(DW,DATE_)
ORDER BY C.CITY

--Sipariþlerin ortalama kargo sürelerini getirme
SELECT
C.CITY,AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_)) AS ORT_KARGO_SÜRELERÝ,ROUND(SUM(O.TOTALPRICE),2) AS TOPLAM_SATIÞ
FROM USERS U 
JOIN ADDRESS A ON U.ID=A.USERID
JOIN ORDERS O ON O.ID= U.ID
JOIN CITIES C ON C.ID=A.CITYID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN INVOICES I ON I.ADDRESSID=A.ID
GROUP BY C.CITY
ORDER BY TOPLAM_SATIÞ


--Tüm kullanýcýlarýn isim, e-posta ve þehir bilgilerini listele
SELECT DISTINCT
U.NAMESURNAME,U.EMAIL,C.CITY
FROM USERS U 
JOIN ADDRESS A ON U.ID=A.USERID
JOIN ORDERS O ON O.ID= U.ID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN CITIES C ON C.ID=A.CITYID
JOIN COUNTRIES CT ON CT.ID=A.COUNTRYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID
ORDER BY U.NAMESURNAME


--Her sipariþin tarihini, toplam tutarýný ve kullanýcý bilgisini listele
SELECT 
U.NAMESURNAME,U.EMAIL,O.DATE_,A.ADDRESSTEXT, U.TELNR1,U.TELNR2, SUM(OD.AMOUNT) AS TOPLAM_MÝKTAR ,SUM(O.TOTALPRICE) AS TOPLAM_SATIÞ
FROM USERS U 
JOIN ADDRESS A ON U.ID=A.USERID
JOIN ORDERS O ON O.ID= U.ID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN CITIES C ON C.ID=A.CITYID
JOIN COUNTRIES CT ON CT.ID=A.COUNTRYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID
GROUP BY U.NAMESURNAME,U.EMAIL,O.DATE_,A.ADDRESSTEXT, U.TELNR1,U.TELNR2
ORDER BY U.NAMESURNAME


--Hangi ürünlerin en fazla satýldýðýný ve toplam satýþ miktarýný gösterme
SELECT TOP 5
I.ItemName, I.CATEGORY1,I.CATEGORY2,SUM(OD.AMOUNT) AS Total_AMOUNT
FROM ITEMS I
JOIN ORDERDETAILS OD ON I.ID=OD.ITEMID
GROUP BY I.ItemName, I.CATEGORY1,I.CATEGORY2
ORDER BY Total_AMOUNT DESC;


--Her ilçede bulunan  kullanýcýlarýn sayýsýný gösterme
SELECT
D.DISTRICT,count(o.USERID) as kullanýcý_sayýsý
FROM USERS U 
JOIN ADDRESS A ON U.ID=A.USERID
JOIN ORDERS O ON O.ID= U.ID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN CITIES C ON C.ID=A.CITYID
JOIN COUNTRIES CT ON CT.ID=A.COUNTRYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID
JOIN ITEMS I ON I.ID=OD.ITEMID
GROUP by D.DISTRICT


--Belirli bir tarih aralýðýnda (örneðin :2019-02-21 ile 2019-02-21) verilen sipariþlerin toplam sayýsýný gösterme
SELECT
CONVERT(DATE,O.DATE_) as tarih  ,count(O.ID) AS Sipariþ_toplam_sayýsý
FROM USERS U 
JOIN ADDRESS A ON U.ID=A.USERID
JOIN ORDERS O ON O.ID= U.ID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN CITIES C ON C.ID=A.CITYID
JOIN COUNTRIES CT ON CT.ID=A.COUNTRYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID
JOIN ITEMS I ON I.ID=OD.ITEMID
where O.DATE_ between '2019-02-21' and '2019-02-21'
GROUP by CONVERT(DATE,O.DATE_)



--belirli bir þehirlerde ("Istanbul" /"Ankara"/"Karabük") verilen tüm sipariþlerin toplam tutarýný listele
SELECT
C.CITY  ,sum(OD.AMOUNT) AS Sipariþ_toplam_tutar
FROM USERS U 
JOIN ADDRESS A ON U.ID=A.USERID
JOIN ORDERS O ON O.ID= U.ID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN CITIES C ON C.ID=A.CITYID
JOIN COUNTRIES CT ON CT.ID=A.COUNTRYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID
JOIN ITEMS I ON I.ID=OD.ITEMID
where C.CITY IN('ÝSTANBUL','ADANA','KARABÜK')
GROUP by C.CITY


--þehir bazýnda en fazla sipariþ verilen ilk 5 þehri göster
SELECT top 5
C.CITY  ,sum(OD.AMOUNT) AS Sipariþ_toplam_tutar
FROM USERS U 
JOIN ADDRESS A ON U.ID=A.USERID
JOIN ORDERS O ON O.ID= U.ID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN CITIES C ON C.ID=A.CITYID
JOIN COUNTRIES CT ON CT.ID=A.COUNTRYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID
JOIN ITEMS I ON I.ID=OD.ITEMID
GROUP by C.CITY
ORDER BY Sipariþ_toplam_tutar DESC


-- kullanýcýlarýn sipariþ baþýna ortalama ne kadar ödeme yaptýðýný gösterme
SELECT 
U.NAMESURNAME,ROUND(AVG(O.TOTALPRICE),2) AS Sipariþ_ortalama_ödeme
FROM USERS U 
JOIN ADDRESS A ON U.ID=A.USERID
JOIN ORDERS O ON O.ID= U.ID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN CITIES C ON C.ID=A.CITYID
JOIN COUNTRIES CT ON CT.ID=A.COUNTRYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID
JOIN ITEMS I ON I.ID=OD.ITEMID
GROUP by U.NAMESURNAME
ORDER BY Sipariþ_ortalama_ödeme DESC


--Ürün  markasýna göre satýþ miktarlarý
SELECT 
ý.BRAND,SUM(OD.AMOUNT) AS SATIÞ_MÝKTARI
FROM USERS U 
JOIN ADDRESS A ON U.ID=A.USERID
JOIN ORDERS O ON O.ID= U.ID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN CITIES C ON C.ID=A.CITYID
JOIN COUNTRIES CT ON CT.ID=A.COUNTRYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID
JOIN ITEMS I ON I.ID=OD.ITEMID
GROUP by I.BRAND
ORDER BY SATIÞ_MÝKTARI DESC



--ülkelere göre verilen toplam sipariþ sayýsýný gösterme
SELECT 
CT.COUNTRY,COUNT(OD.ORDERID) AS SÝPARÝÞ_SAYISI
FROM USERS U 
JOIN ADDRESS A ON U.ID=A.USERID
JOIN ORDERS O ON O.ID= U.ID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN CITIES C ON C.ID=A.CITYID
JOIN COUNTRIES CT ON CT.ID=A.COUNTRYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID
JOIN ITEMS I ON I.ID=OD.ITEMID
GROUP by CT.COUNTRY
ORDER BY  SÝPARÝÞ_SAYISI DESC


